"""
Lots of component in OMTK were generated by script.
Now that we have real component functionnality thoses scripts are not needed anymore.
This directory is here for archival purpose in case running the generation script is more usefull than manipulating the nodes directly.
"""

