# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rll/dev/python/omtk/python/omtk/qt_widgets/ui/form_create_component.ui'
#
# Created: Sat Feb  3 16:48:39 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from omtk.vendor.Qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton_select = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select.setObjectName("pushButton_select")
        self.horizontalLayout_2.addWidget(self.pushButton_select)
        self.pushButton_create = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout_2.addWidget(self.pushButton_create)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_version = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_version.setObjectName("lineEdit_version")
        self.gridLayout.addWidget(self.lineEdit_version, 2, 2, 1, 1)
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.label_author = QtWidgets.QLabel(self.centralwidget)
        self.label_author.setObjectName("label_author")
        self.gridLayout.addWidget(self.label_author, 1, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 2, 1, 1)
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setObjectName("label_version")
        self.gridLayout.addWidget(self.label_version, 2, 0, 1, 1)
        self.lineEdit_author = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.gridLayout.addWidget(self.lineEdit_author, 1, 2, 1, 1)
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setObjectName("label_id")
        self.gridLayout.addWidget(self.label_id, 3, 0, 1, 1)
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.gridLayout.addWidget(self.lineEdit_id, 3, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ctrl = QtWidgets.QLabel(self.centralwidget)
        self.label_ctrl.setObjectName("label_ctrl")
        self.verticalLayout.addWidget(self.label_ctrl)
        self.widget_view_ctrl = WidgetCreateComponentWizardParts(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_view_ctrl.sizePolicy().hasHeightForWidth())
        self.widget_view_ctrl.setSizePolicy(sizePolicy)
        self.widget_view_ctrl.setObjectName("widget_view_ctrl")
        self.verticalLayout.addWidget(self.widget_view_ctrl)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_infl = QtWidgets.QLabel(self.centralwidget)
        self.label_infl.setObjectName("label_infl")
        self.verticalLayout_2.addWidget(self.label_infl)
        self.widget_view_infl = WidgetCreateComponentWizardParts(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_view_infl.sizePolicy().hasHeightForWidth())
        self.widget_view_infl.setSizePolicy(sizePolicy)
        self.widget_view_infl.setObjectName("widget_view_infl")
        self.verticalLayout_2.addWidget(self.widget_view_infl)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_guid = QtWidgets.QLabel(self.centralwidget)
        self.label_guid.setObjectName("label_guid")
        self.verticalLayout_3.addWidget(self.label_guid)
        self.widget_view_guid = WidgetCreateComponentWizardParts(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_view_guid.sizePolicy().hasHeightForWidth())
        self.widget_view_guid.setSizePolicy(sizePolicy)
        self.widget_view_guid.setObjectName("widget_view_guid")
        self.verticalLayout_3.addWidget(self.widget_view_guid)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_submit.sizePolicy().hasHeightForWidth())
        self.pushButton_submit.setSizePolicy(sizePolicy)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.verticalLayout_4.addWidget(self.pushButton_submit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Publisher", None, -1))
        self.pushButton_select.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.pushButton_create.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.label_name.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.label_author.setText(QtWidgets.QApplication.translate("MainWindow", "Author", None, -1))
        self.label_version.setText(QtWidgets.QApplication.translate("MainWindow", "Version", None, -1))
        self.label_id.setText(QtWidgets.QApplication.translate("MainWindow", "Unique ID", None, -1))
        self.label_ctrl.setText(QtWidgets.QApplication.translate("MainWindow", "Ctrls:", None, -1))
        self.label_infl.setText(QtWidgets.QApplication.translate("MainWindow", "Influences:", None, -1))
        self.label_guid.setText(QtWidgets.QApplication.translate("MainWindow", "Guides:", None, -1))
        self.pushButton_submit.setText(QtWidgets.QApplication.translate("MainWindow", "Publish", None, -1))

from ..widget_component_wizard import WidgetCreateComponentWizardParts
