# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rll/dev/python/omtk/python/omtk/ui/main_window.ui'
#
# Created: Wed Jul 12 11:39:46 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_OpenRiggingToolkit(object):
    def setupUi(self, OpenRiggingToolkit):
        OpenRiggingToolkit.setObjectName("OpenRiggingToolkit")
        OpenRiggingToolkit.resize(620, 600)
        self.centralwidget = QtGui.QWidget(OpenRiggingToolkit)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page_1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_welcome = WidgetWelcome(self.page_1)
        self.widget_welcome.setObjectName("widget_welcome")
        self.verticalLayout_9.addWidget(self.widget_welcome)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_node_editor = NodeGraphWidget(self.page_2)
        self.widget_node_editor.setObjectName("widget_node_editor")
        self.verticalLayout_7.addWidget(self.widget_node_editor)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        OpenRiggingToolkit.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OpenRiggingToolkit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRig = QtGui.QMenu(self.menubar)
        self.menuRig.setObjectName("menuRig")
        self.menuJoint = QtGui.QMenu(self.menubar)
        self.menuJoint.setObjectName("menuJoint")
        self.menuInfluences = QtGui.QMenu(self.menubar)
        self.menuInfluences.setObjectName("menuInfluences")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuComponents = QtGui.QMenu(self.menubar)
        self.menuComponents.setObjectName("menuComponents")
        OpenRiggingToolkit.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OpenRiggingToolkit)
        self.statusbar.setObjectName("statusbar")
        OpenRiggingToolkit.setStatusBar(self.statusbar)
        self.dockWidget_logger = QtGui.QDockWidget(OpenRiggingToolkit)
        self.dockWidget_logger.setObjectName("dockWidget_logger")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_logger = WidgetLogger(self.dockWidgetContents)
        self.widget_logger.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_logger.sizePolicy().hasHeightForWidth())
        self.widget_logger.setSizePolicy(sizePolicy)
        self.widget_logger.setObjectName("widget_logger")
        self.verticalLayout_4.addWidget(self.widget_logger)
        self.dockWidget_logger.setWidget(self.dockWidgetContents)
        OpenRiggingToolkit.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_logger)
        self.dockWidget_modules = QtGui.QDockWidget(OpenRiggingToolkit)
        self.dockWidget_modules.setMinimumSize(QtCore.QSize(120, 50))
        self.dockWidget_modules.setObjectName("dockWidget_modules")
        self.dockWidgetContents_modules = QtGui.QWidget()
        self.dockWidgetContents_modules.setObjectName("dockWidgetContents_modules")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_modules)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_modules = WidgetListModules(self.dockWidgetContents_modules)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modules.sizePolicy().hasHeightForWidth())
        self.widget_modules.setSizePolicy(sizePolicy)
        self.widget_modules.setObjectName("widget_modules")
        self.verticalLayout_6.addWidget(self.widget_modules)
        self.dockWidget_modules.setWidget(self.dockWidgetContents_modules)
        OpenRiggingToolkit.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_modules)
        self.dockWidget_influences = QtGui.QDockWidget(OpenRiggingToolkit)
        self.dockWidget_influences.setMinimumSize(QtCore.QSize(120, 50))
        self.dockWidget_influences.setObjectName("dockWidget_influences")
        self.dockWidgetContents_jnts = QtGui.QWidget()
        self.dockWidgetContents_jnts.setObjectName("dockWidgetContents_jnts")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.dockWidgetContents_jnts)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_jnts = WidgetListInfluences(self.dockWidgetContents_jnts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_jnts.sizePolicy().hasHeightForWidth())
        self.widget_jnts.setSizePolicy(sizePolicy)
        self.widget_jnts.setObjectName("widget_jnts")
        self.verticalLayout_8.addWidget(self.widget_jnts)
        self.dockWidget_influences.setWidget(self.dockWidgetContents_jnts)
        OpenRiggingToolkit.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_influences)
        self.dockWidget_meshes = QtGui.QDockWidget(OpenRiggingToolkit)
        self.dockWidget_meshes.setMinimumSize(QtCore.QSize(120, 50))
        self.dockWidget_meshes.setObjectName("dockWidget_meshes")
        self.dockWidgetContents_meshes = QtGui.QWidget()
        self.dockWidgetContents_meshes.setObjectName("dockWidgetContents_meshes")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.dockWidgetContents_meshes)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_meshes = WidgetListMeshes(self.dockWidgetContents_meshes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_meshes.sizePolicy().hasHeightForWidth())
        self.widget_meshes.setSizePolicy(sizePolicy)
        self.widget_meshes.setObjectName("widget_meshes")
        self.verticalLayout_10.addWidget(self.widget_meshes)
        self.dockWidget_meshes.setWidget(self.dockWidgetContents_meshes)
        OpenRiggingToolkit.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_meshes)
        self.actionUpdate = QtGui.QAction(OpenRiggingToolkit)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionImport = QtGui.QAction(OpenRiggingToolkit)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtGui.QAction(OpenRiggingToolkit)
        self.actionExport.setObjectName("actionExport")
        self.actionBuildAll = QtGui.QAction(OpenRiggingToolkit)
        self.actionBuildAll.setObjectName("actionBuildAll")
        self.actionUnbuildAll = QtGui.QAction(OpenRiggingToolkit)
        self.actionUnbuildAll.setObjectName("actionUnbuildAll")
        self.actionRebuildAll = QtGui.QAction(OpenRiggingToolkit)
        self.actionRebuildAll.setObjectName("actionRebuildAll")
        self.actionCreateModule = QtGui.QAction(OpenRiggingToolkit)
        self.actionCreateModule.setObjectName("actionCreateModule")
        self.actionAddNodeToModule = QtGui.QAction(OpenRiggingToolkit)
        self.actionAddNodeToModule.setObjectName("actionAddNodeToModule")
        self.actionRemoveNodeFromModule = QtGui.QAction(OpenRiggingToolkit)
        self.actionRemoveNodeFromModule.setObjectName("actionRemoveNodeFromModule")
        self.actionMirrorJntsLToR = QtGui.QAction(OpenRiggingToolkit)
        self.actionMirrorJntsLToR.setObjectName("actionMirrorJntsLToR")
        self.actionMirrorJntsRToL = QtGui.QAction(OpenRiggingToolkit)
        self.actionMirrorJntsRToL.setObjectName("actionMirrorJntsRToL")
        self.actionMirrorSelection = QtGui.QAction(OpenRiggingToolkit)
        self.actionMirrorSelection.setObjectName("actionMirrorSelection")
        self.actionShowPluginManager = QtGui.QAction(OpenRiggingToolkit)
        self.actionShowPluginManager.setObjectName("actionShowPluginManager")
        self.actionShowPreferences = QtGui.QAction(OpenRiggingToolkit)
        self.actionShowPreferences.setObjectName("actionShowPreferences")
        self.actionCreateComponent = QtGui.QAction(OpenRiggingToolkit)
        self.actionCreateComponent.setObjectName("actionCreateComponent")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionUpdate)
        self.menuRig.addAction(self.actionBuildAll)
        self.menuRig.addAction(self.actionUnbuildAll)
        self.menuRig.addAction(self.actionRebuildAll)
        self.menuJoint.addAction(self.actionCreateModule)
        self.menuJoint.addAction(self.actionAddNodeToModule)
        self.menuJoint.addAction(self.actionRemoveNodeFromModule)
        self.menuInfluences.addAction(self.actionMirrorJntsLToR)
        self.menuInfluences.addAction(self.actionMirrorJntsRToL)
        self.menuInfluences.addAction(self.actionMirrorSelection)
        self.menuSettings.addAction(self.actionShowPreferences)
        self.menuSettings.addAction(self.actionShowPluginManager)
        self.menuComponents.addAction(self.actionCreateComponent)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRig.menuAction())
        self.menubar.addAction(self.menuJoint.menuAction())
        self.menubar.addAction(self.menuInfluences.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuComponents.menuAction())

        self.retranslateUi(OpenRiggingToolkit)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OpenRiggingToolkit)

    def retranslateUi(self, OpenRiggingToolkit):
        OpenRiggingToolkit.setWindowTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Open Rigging Toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Fi&le", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRig.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Ri&g", None, QtGui.QApplication.UnicodeUTF8))
        self.menuJoint.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Mo&dules", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfluences.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "I&nfluences", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponents.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_modules.setWindowTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_influences.setWindowTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Influences", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_meshes.setWindowTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Update All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setToolTip(QtGui.QApplication.translate("OpenRiggingToolkit", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuildAll.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Build All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnbuildAll.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Unbuild All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRebuildAll.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Rebuild All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateModule.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Create Module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddNodeToModule.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Add Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveNodeFromModule.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Remove Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirrorJntsLToR.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Mirror L -> R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirrorJntsRToL.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Mirror &R -> L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirrorSelection.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Mirror &using Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPluginManager.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Plugin &Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPreferences.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "&Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateComponent.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Create New", None, QtGui.QApplication.UnicodeUTF8))

from ..widget_list_meshes import WidgetListMeshes
from ..widget_logger import WidgetLogger
from ..nodegraph_widget.nodegraph_widget import NodeGraphWidget
from ..widget_list_modules import WidgetListModules
from ..widget_welcome import WidgetWelcome
from ..widget_list_influences import WidgetListInfluences
