# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rll/packages/omtk/9.9.9/omtk/ui/main_window.ui'
#
# Created: Sun Oct 16 09:39:35 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_OpenRiggingToolkit(object):
    def setupUi(self, OpenRiggingToolkit):
        OpenRiggingToolkit.setObjectName("OpenRiggingToolkit")
        OpenRiggingToolkit.resize(787, 658)
        self.centralwidget = QtGui.QWidget(OpenRiggingToolkit)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_modules = QtGui.QLabel(self.layoutWidget)
        self.label_modules.setObjectName("label_modules")
        self.verticalLayout.addWidget(self.label_modules)
        self.widget_modules = WidgetListModules(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modules.sizePolicy().hasHeightForWidth())
        self.widget_modules.setSizePolicy(sizePolicy)
        self.widget_modules.setObjectName("widget_modules")
        self.verticalLayout.addWidget(self.widget_modules)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_jnts = QtGui.QLabel(self.layoutWidget1)
        self.label_jnts.setObjectName("label_jnts")
        self.verticalLayout_2.addWidget(self.label_jnts)
        self.widget_jnts = WidgetListInfluences(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_jnts.sizePolicy().hasHeightForWidth())
        self.widget_jnts.setSizePolicy(sizePolicy)
        self.widget_jnts.setObjectName("widget_jnts")
        self.verticalLayout_2.addWidget(self.widget_jnts)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.widget_meshes = WidgetListMeshes(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_meshes.sizePolicy().hasHeightForWidth())
        self.widget_meshes.setSizePolicy(sizePolicy)
        self.widget_meshes.setObjectName("widget_meshes")
        self.verticalLayout_3.addWidget(self.widget_meshes)
        self.verticalLayout_5.addWidget(self.splitter)
        OpenRiggingToolkit.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OpenRiggingToolkit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRig = QtGui.QMenu(self.menubar)
        self.menuRig.setObjectName("menuRig")
        self.menuJoint = QtGui.QMenu(self.menubar)
        self.menuJoint.setObjectName("menuJoint")
        self.menuInfluences = QtGui.QMenu(self.menubar)
        self.menuInfluences.setObjectName("menuInfluences")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        OpenRiggingToolkit.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OpenRiggingToolkit)
        self.statusbar.setObjectName("statusbar")
        OpenRiggingToolkit.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(OpenRiggingToolkit)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_logger = WidgetLogger(self.dockWidgetContents)
        self.widget_logger.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_logger.sizePolicy().hasHeightForWidth())
        self.widget_logger.setSizePolicy(sizePolicy)
        self.widget_logger.setObjectName("widget_logger")
        self.verticalLayout_4.addWidget(self.widget_logger)
        self.dockWidget.setWidget(self.dockWidgetContents)
        OpenRiggingToolkit.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.actionUpdate = QtGui.QAction(OpenRiggingToolkit)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionImport = QtGui.QAction(OpenRiggingToolkit)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtGui.QAction(OpenRiggingToolkit)
        self.actionExport.setObjectName("actionExport")
        self.actionBuildAll = QtGui.QAction(OpenRiggingToolkit)
        self.actionBuildAll.setObjectName("actionBuildAll")
        self.actionUnbuildAll = QtGui.QAction(OpenRiggingToolkit)
        self.actionUnbuildAll.setObjectName("actionUnbuildAll")
        self.actionRebuildAll = QtGui.QAction(OpenRiggingToolkit)
        self.actionRebuildAll.setObjectName("actionRebuildAll")
        self.actionCreateModule = QtGui.QAction(OpenRiggingToolkit)
        self.actionCreateModule.setObjectName("actionCreateModule")
        self.actionAddNodeToModule = QtGui.QAction(OpenRiggingToolkit)
        self.actionAddNodeToModule.setObjectName("actionAddNodeToModule")
        self.actionRemoveNodeFromModule = QtGui.QAction(OpenRiggingToolkit)
        self.actionRemoveNodeFromModule.setObjectName("actionRemoveNodeFromModule")
        self.actionMirrorJntsLToR = QtGui.QAction(OpenRiggingToolkit)
        self.actionMirrorJntsLToR.setObjectName("actionMirrorJntsLToR")
        self.actionMirrorJntsRToL = QtGui.QAction(OpenRiggingToolkit)
        self.actionMirrorJntsRToL.setObjectName("actionMirrorJntsRToL")
        self.actionMirrorSelection = QtGui.QAction(OpenRiggingToolkit)
        self.actionMirrorSelection.setObjectName("actionMirrorSelection")
        self.actionShowPluginManager = QtGui.QAction(OpenRiggingToolkit)
        self.actionShowPluginManager.setObjectName("actionShowPluginManager")
        self.actionShowPreferences = QtGui.QAction(OpenRiggingToolkit)
        self.actionShowPreferences.setObjectName("actionShowPreferences")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionUpdate)
        self.menuRig.addAction(self.actionBuildAll)
        self.menuRig.addAction(self.actionUnbuildAll)
        self.menuRig.addAction(self.actionRebuildAll)
        self.menuJoint.addAction(self.actionCreateModule)
        self.menuJoint.addAction(self.actionAddNodeToModule)
        self.menuJoint.addAction(self.actionRemoveNodeFromModule)
        self.menuInfluences.addAction(self.actionMirrorJntsLToR)
        self.menuInfluences.addAction(self.actionMirrorJntsRToL)
        self.menuInfluences.addAction(self.actionMirrorSelection)
        self.menuSettings.addAction(self.actionShowPreferences)
        self.menuSettings.addAction(self.actionShowPluginManager)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRig.menuAction())
        self.menubar.addAction(self.menuJoint.menuAction())
        self.menubar.addAction(self.menuInfluences.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(OpenRiggingToolkit)
        QtCore.QMetaObject.connectSlotsByName(OpenRiggingToolkit)

    def retranslateUi(self, OpenRiggingToolkit):
        OpenRiggingToolkit.setWindowTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Open Rigging Toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_modules.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.label_jnts.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Influences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRig.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.menuJoint.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfluences.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Influences", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("OpenRiggingToolkit", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Update All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setToolTip(QtGui.QApplication.translate("OpenRiggingToolkit", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuildAll.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Build All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnbuildAll.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Unbuild All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRebuildAll.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Rebuild All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateModule.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Create Module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddNodeToModule.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Add Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveNodeFromModule.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Remove Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirrorJntsLToR.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Mirror L -> R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirrorJntsRToL.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Mirror R -> L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirrorSelection.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Mirror using Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPluginManager.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Plugin Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPreferences.setText(QtGui.QApplication.translate("OpenRiggingToolkit", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

from ..widget_logger import WidgetLogger
from ..widget_list_modules import WidgetListModules
from ..widget_list_meshes import WidgetListMeshes
from ..widget_list_influences import WidgetListInfluences
